# Generated by Django 4.2.5 on 2023-10-02 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('stage', models.CharField(choices=[('начальная', 'начальная'), ('разгар', 'разгар'), ('исход', 'исход'), ('хроническая', 'хроническая')], max_length=20, verbose_name='Стадия')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('dosa', models.IntegerField(verbose_name='Дозировка')),
                ('period', models.IntegerField(verbose_name='Срок приёма')),
            ],
        ),
        migrations.CreateModel(
            name='Poroda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20, verbose_name='Вид')),
                ('poroda', models.CharField(max_length=20, verbose_name='Порода')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Кличка')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('disease', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.disease', verbose_name='Заболевание')),
                ('medicine', models.ManyToManyField(to='catalog.medicine', verbose_name='Лекарство')),
                ('poroda', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.poroda', verbose_name='Порода')),
            ],
        ),
    ]
